stdout of test 'tst302` in directory 'monetdb5/mal` itself:


# 08:01:15 >  
# 08:01:15 >  Mtimeout -timeout 60 Mserver "--config=/ufs/mk/monet5/Linux/etc/MonetDB5.conf" --debug=10 --set "monet_mod_path=/ufs/mk/monet5/Linux/lib/MonetDB5:/ufs/mk/opensource/MonetDB/Linux/lib/MonetDB" --set "gdk_dbfarm=/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm" --set "sql_logdir=/ufs/mk/monet5/Linux/var/MonetDB5/log" --set mapi_port=42158 --set sql_port=55708 --set monet_prompt= --trace "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --dbname=mTests_src_mal  tst302.mal </dev/null
# 08:01:15 >  

# MonetDB Server v4.99.19
# Copyright (c) 1993-2006 CWI, all rights reserved
# Compiled for x86_64-pc-linux-gnu/64bit with 64bit OIDs dynamically linked
# dbname:mTests_src_mal
# Visit http://monetdb.cwi.nl/ for further information.
##propagate INT exception
## (you should be able to pass it upwards though)
#raise	IllegalAccess := 1234;
#	print("should not come here\n");
#
function user.main():void;
#propagate INT exception 
# (you should be able to pass it upwards though) 
    raise PermissionDeniedException := 1234;
    io.print("should not come here\n");
end main;
!MALException:user.main[5]:Exception not caught






# 17:45:29 >  
# 17:45:29 >  Done.
# 17:45:29 >  

