stdout of test 'tst607` in directory 'monetdb5/mal` itself:


# 14:53:38 >  
# 14:53:38 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "gdk_dbfarm=/net/sofia.ins.cwi.nl/export/scratch1/fabian/tmp/mtest-Oct2012-sofia.ins.cwi.nl/five/dbfarm" "--set" "mapi_open=true" "--set" "mapi_port=30254" "--set" "monet_prompt=" "--trace" "--forcemito" "--set" "mal_listing=2" "--dbname=mTests_mal" "tst607.mal"
# 14:53:38 >  

# MonetDB 5 server v11.13.0 "Oct2012-b3df9ec1a3e0+"
# Serving database 'mTests_mal', using 8 threads
# Compiled for x86_64-pc-linux-gnu/64bit with 64bit OIDs dynamically linked
# Found 15.629 GiB available main-memory.
# Copyright (c) 1993-July 2008 CWI.
# Copyright (c) August 2008-2013 MonetDB B.V., all rights reserved
# Visit http://www.monetdb.org/ for further information
# Listening for connection requests on mapi:monetdb://sofia.ins.cwi.nl:30254/
# MonetDB/GIS module loaded
# MonetDB/JAQL module loaded
# MonetDB/SQL module loaded
# MonetDB/DataCell loaded
function user.main():void;
# using spaces 
    roomnumber := 321;
    const.deposit("roomnumber",roomnumber);
    v:int  := const.take("roomnumber");
    io.print(v);
    v:int  := 123;
    v:int  := calc.+(v,1);
    const.release("roomnumber");
    io.print("attempt twice to release");
    const.release("roomnumber");
# failure? done twice or implicit take? 
end main;
[ 321 ]
[ "attempt twice to release" ]

# 14:53:38 >  
# 14:53:38 >  "Done."
# 14:53:38 >  

